### ISSUE TITLE
카메라 사진 값 전달 오류

### ISSUE THREAD

**Issue by jiiiiiyoon** [JobSeek-Void/ic-ec#47]
카메라로 사진을 찍은 후 찍은 이미지의 값이 다음 액티비티로 전달되지 않는 오류

**Comment by ham2174** [comment]
@jiiiiiyoon 해당 부분 이슈 해결은 작업중이 아니라면 제가 가져가도 될까요?

**Comment by jiiiiiyoon** [comment]
@ham2174 넵넵 알겠습니다~ :)
